<?php

/**
 * @file
 * Message notify.
 */

/**
 * Implements hook_message_view().
 */
function message_notify_message_view($message, $view_mode, $langcode) {
  if ($message->getType()->category == 'message_type_email') {
    $message->content['subject'] = array(
      // Add the subject field.
      '#markup' => $message->getText($langcode, array('field name' => 'message_text_subject')),
    );
  }
}

/**
 * Implements hook_default_message_type_category().
 */
function message_notify_default_message_type_category() {
  $items = array();
  $items['message_type_email'] = entity_import('message_type_category', '{
    "category" : "message_type_email",
    "description" : "Message type email",
    "statusKey" : "status",
    "rdf_mapping" : []
  }');
  return $items;
}

/**
 * Implements hook_mail().
 *
 * Set's the message subject and body as configured.
 */
function message_notify_mail($key, &$message, $params) {
  $message_entity = $params['message'];
  $element = $message_entity->buildContent();

  // TODO: Subject should be plain text.
  $message['subject'] = strip_tags(str_replace(array("\r", "\n"), '', drupal_render($element['subject'])));
  $message['body'][] = drupal_render($element['text']);
}