<?php
/**
 * @file
 * Message notify module.
 */

/**
 * Implements hook_mail().
 *
 * Set's the message subject and body as configured.
 */
function message_notify_mail($key, &$message, $params) {
  $message['subject'] = $params['mail_title'];
  $message['body'][] = $params['mail_body'];
}

/**
 * Implements hook_entity_bundle_create().
 *
 * We cannot easily set the the visibilty of extra fields, so we set the
 * bundle settings upon creation of new message bundle.
 */
function message_notify_entity_bundle_create($entity_type_id, $bundle) {
  if ($entity_type_id != 'message') {
    return;
  }

  // Setup the subject and body display modes.
  // @todo
}
